/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abilities: typeof import('./src/components/help/Abilities.vue')['default']
    Ability: typeof import('./src/components/Ability.vue')['default']
    Activation: typeof import('./src/components/help/Activation.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Cards: typeof import('./src/components/help/Cards.vue')['default']
    Collection: typeof import('./src/components/Collection.vue')['default']
    CollectionJoker: typeof import('./src/components/CollectionJoker.vue')['default']
    Compatibility: typeof import('./src/components/help/Compatibility.vue')['default']
    Correctness: typeof import('./src/components/Correctness.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Eternal: typeof import('./src/components/Eternal.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    GeneralInfo: typeof import('./src/components/help/GeneralInfo.vue')['default']
    Guess: typeof import('./src/components/Guess.vue')['default']
    GuessInfo: typeof import('./src/components/GuessInfo.vue')['default']
    GuessInfoAttribute: typeof import('./src/components/GuessInfoAttribute.vue')['default']
    Hands: typeof import('./src/components/help/Hands.vue')['default']
    HelpDialog: typeof import('./src/components/HelpDialog.vue')['default']
    ICharmBook: typeof import('~icons/charm/book')['default']
    ICharmChartLine: typeof import('~icons/charm/chart-line')['default']
    ICharmChevronDown: typeof import('~icons/charm/chevron-down')['default']
    ICharmChevronsUp: typeof import('~icons/charm/chevrons-up')['default']
    ICharmChevronUp: typeof import('~icons/charm/chevron-up')['default']
    ICharmCircleCross: typeof import('~icons/charm/circle-cross')['default']
    ICharmCircleTick: typeof import('~icons/charm/circle-tick')['default']
    ICharmClipboard: typeof import('~icons/charm/clipboard')['default']
    ICharmClipboardTick: typeof import('~icons/charm/clipboard-tick')['default']
    ICharmClock: typeof import('~icons/charm/clock')['default']
    ICharmCross: typeof import('~icons/charm/cross')['default']
    ICharmCrosshair: typeof import('~icons/charm/crosshair')['default']
    ICharmEye: typeof import('~icons/charm/eye')['default']
    ICharmHelp: typeof import('~icons/charm/help')['default']
    ICharmInfinity: typeof import('~icons/charm/infinity')['default']
    ICharmInfo: typeof import('~icons/charm/info')['default']
    ICharmNorthStar: typeof import('~icons/charm/north-star')['default']
    ICharmRefresh: typeof import('~icons/charm/refresh')['default']
    ICharmSearch: typeof import('~icons/charm/search')['default']
    ICharmShare: typeof import('~icons/charm/share')['default']
    ICharmSkull: typeof import('~icons/charm/skull')['default']
    ICharmStickyNote: typeof import('~icons/charm/sticky-note')['default']
    ICharmSwapVertical: typeof import('~icons/charm/swap-vertical')['default']
    ICharmTick: typeof import('~icons/charm/tick')['default']
    ILucideArrowDownAZ: typeof import('~icons/lucide/arrow-down-a-z')['default']
    ILucideArrowDownNarrowWide: typeof import('~icons/lucide/arrow-down-narrow-wide')['default']
    ILucideClub: typeof import('~icons/lucide/club')['default']
    ILucideDiamond: typeof import('~icons/lucide/diamond')['default']
    ILucideHeart: typeof import('~icons/lucide/heart')['default']
    ILucideSpade: typeof import('~icons/lucide/spade')['default']
    JokerCard: typeof import('./src/components/JokerCard.vue')['default']
    Perishable: typeof import('./src/components/Perishable.vue')['default']
    Rarity: typeof import('./src/components/Rarity.vue')['default']
    RarityButton: typeof import('./src/components/RarityButton.vue')['default']
    RarityHelp: typeof import('./src/components/help/RarityHelp.vue')['default']
    Scrollable: typeof import('./src/components/Scrollable.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Share: typeof import('./src/components/Share.vue')['default']
    Sticker: typeof import('./src/components/Sticker.vue')['default']
    Suit: typeof import('./src/components/Suit.vue')['default']
    TimeLeft: typeof import('./src/components/TimeLeft.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    UndiscoveredJokerCard: typeof import('./src/components/UndiscoveredJokerCard.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
    WinDialog: typeof import('./src/components/WinDialog.vue')['default']
  }
}
